accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),


]

olx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('products/', include('product.urls', namespace='products')),
    # path('accounts/', include('accounts.urls', namespace='accounts')),
    
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views


app_name = 'product'

urlpatterns = [
    path('', views.productlist, name='product_list'),
    path('<slug:category_slug>', views.productlist, name='product_list_category'),
    path('detail/<slug:product_slug>', views.productdetail, name='product_detail'),
]

accounts/models.py
from django.db import models

# Create your models here.

product/models.py
from contextlib import nullcontext
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.utils.text import slugify
# Create your models here.

class Product(models.Model):
  
  CONDITION_TYPE = (
    ("New", "New") ,
    ("Used", "Used")
  )
  
  city_choice = (
  ('Alexandria', 'Alexandria'),
  ('Aswan', 'Aswan'),
  ('Asyut', 'Asyut'),
  ('Beheira', 'Beheira'),
  ('Beni Suef', 'Beni Suef'),
  ('Cairo', 'Cairo'),
  ('Dakahlia', 'Dakahlia'),
  ('Damietta', 'Damietta'),
  ('Fayoum', 'Fayoum'),
  ('Gharbia', 'Gharbia'),
  ('Giaz', 'Giza'),
  ('Ismailia', 'Ismailia'),
  ('Kafr al-Sheikh', 'Kafr al-Sheikh'),
  ('Luxor', 'Luxor'),
  ('Matruh', 'Matruh'),
  ('Minya', 'Minya'),
  ('Monufia', 'Monufia'),
  ('New Valley', 'New Valley'),
  ('Port Said', 'Port Said'),
  ('Qalyubia', 'Qalyubia'),
  ('Qena', 'Qena'),
  ('Red Sea', 'Red Sea'),
  ('Sharqia', 'Sharqia'),
  ('Sohag', 'Sohag'),
  ('South Sinai', 'South Sinai'),
  ('Suez', 'Suez'),
  )
  
  
  name = models.CharField(max_length=100)
  owner = models.ForeignKey(User, on_delete=models.CASCADE)
  description = RichTextField()
  condition = models.CharField(max_length=100, choices=CONDITION_TYPE)
  category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
  brand = models.ForeignKey('Brand', on_delete=models.SET_NULL, null=True)
  city = models.CharField(choices=city_choice, max_length=100)
  price = models.IntegerField()
  image = models.ImageField(upload_to='main_product/', blank=True, null=True)
  created_date = models.DateTimeField(default=timezone.now)
  slug = models.SlugField(blank=True, null=True)
  
  def save(self, *args, **kwargs):
    if not self.slug and self.name :
      self.slug = slugify(self.name)
    super(Product, self).save(*args, **kwargs)
  
  def __str__(self):
    return self.name
  
  
class ProductImages(models.Model):
  product = models.ForeignKey(Product, on_delete=models.CASCADE)
  image = models.ImageField(upload_to='products/', blank=True, null=True)
  
  
  class Meta:
    verbose_name = 'Product Image'
    verbose_name_plural = 'Product Images'
    
    
  def __str__(self):
    return self.product.name
  
  
class Category(models.Model):
  category_name = models.CharField(max_length=50)
  image = models.ImageField(upload_to='category/', blank=True, null=True)
  slug = models.SlugField(blank=True, null=True)
  
  def save(self, *args, **kwargs):
    if not self.slug and self.category_name : 
      self.slug = slugify(self.category_name)
    super(Category, self).save(*args, **kwargs)
  
  
  class Meta:
    verbose_name = 'category'
    verbose_name_plural = 'categories'
    
  def __str__(self):
    return self.category_name
  
  

class Brand(models.Model):
  brand_name = models.CharField(max_length=50)
  
  class Meta:
    verbose_name = 'brand'
    verbose_name_plural = 'brands'
    
  def __str__(self):
    return self.brand_name

accounts/views.py
from django.shortcuts import render

# Create your views here.

product/views.py
from django.shortcuts import render
from .models import Product, ProductImages, Category
from django.core.paginator import Paginator
from django.db.models import Count
from django.db.models import Q
from django.shortcuts import get_object_or_404

# Create your views here.

def productlist(request, category_slug=None):
  category = None
  productlist = Product.objects.all()
  categorylist = Category.objects.annotate(total_products=Count('product'))
  
  if category_slug :
    category = get_object_or_404(Category, slug=category_slug)
    productlist = productlist.filter(category=category)
    
  search_query = request.GET.get('q')
  if search_query :
    productlist = productlist.filter(
      Q(name__icontains = search_query)|
      Q(description__icontains = search_query)|
      Q(condition__icontains = search_query)|
      Q(brand__brand_name__icontains = search_query)|
      Q(category__category_name__icontains = search_query)
    )
  
  paginator = Paginator(productlist, 2) 
  page_number = request.GET.get('page')
  productlist = paginator.get_page(page_number) 
  template = 'Product/product_list.html'
  context = {'product_list' : productlist, 'category_list' : categorylist, 'category' : category}
  
  return render(request, template, context)
  


def productdetail(request, product_slug):
  productdetail = get_object_or_404(Product, slug=product_slug)
  productimages = ProductImages.objects.filter(product=productdetail)
  template = 'Product/product_detail.html'
  context = {'product_detail': productdetail, 'product_images': productimages}

  return render(request, template, context)

accounts/templates/base_accounts.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Resale a Business Category Flat Bootstrap Responsive Website Template | Home :: w3layouts</title>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-select.css' %}">
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Resale Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<!--fonts-->
<link href='//fonts.googleapis.com/css?family=Ubuntu+Condensed' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!--//fonts-->	
<!-- js -->
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<!-- js -->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/bootstrap-select.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script>
  $(document).ready(function () {
    var mySelect = $('#first-disabled2');

    $('#special').on('click', function () {
      mySelect.find('option:selected').prop('disabled', true);
      mySelect.selectpicker('refresh');
    });

    $('#special2').on('click', function () {
      mySelect.find('option:disabled').prop('disabled', false);
      mySelect.selectpicker('refresh');
    });

    $('#basic2').selectpicker({
      liveSearch: true,
      maxOptions: 1
    });
  });
</script>
<script type="text/javascript" src="{% static 'js/jquery.leanModal.min.js' %}"></script>
<link href="{% static 'css/jquery.uls.css' %}" rel="stylesheet"/>
<link href="{% static 'css/jquery.uls.grid.css' %}" rel="stylesheet"/>
<link href="{% static 'css/jquery.uls.lcd.css' %}" rel="stylesheet"/>
<!-- Source -->
<script src="{% static 'js/jquery.uls.data.utils.js' %}"></script>
<script src="{% static 'js/jquery.uls.data.js' %}"></script>
<script src="{% static 'js/jquery.uls.lcd.js' %}"></script>
<script src="{% static 'js/jquery.uls.languagefilter.js' %}"></script>
<script src="{% static 'js/jquery.uls.regionfilter.js' %}"></script>
<script src="{% static 'js/jquery.uls.core.js' %}"></script>
<script>
			$( document ).ready( function() {
				$( '.uls-trigger' ).uls( {
					onSelect : function( language ) {
						var languageName = $.uls.data.getAntonym( language );
						$( '.uls-trigger' ).text( languageName );
					},
					quickList: ['en', 'hi', 'he', 'ml', 'ta', 'fr'] //FIXME
				} );
			} );
</script>
</head>
<body>
	<div class="header">
		<div class="container">
			<div class="logo">
				<a href="index.html"><span>Re</span>sale</a>
			</div>
			<div class="header-right">
			<a class="account" href="login.html">My Account</a>
			<span class="active uls-trigger">Select language</span>
	<!-- Large modal -->
		</div>
		</div>
	</div>

		<!-- content-starts-here -->
{% block body %}
	
{% endblock body %}
		<!--footer section start-->		
		<footer>
			<div class="footer-top">
				<div class="container">
					<div class="foo-grids">
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Who We Are</h4>
							<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
							<p>The point of using Lorem Ipsum is that it has a more-or-less normal letters, as opposed to using 'Content here.</p>
						</div>
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Help</h4>
							<ul>
								<li><a href="howitworks.html">How it Works</a></li>						
								<li><a href="sitemap.html">Sitemap</a></li>
								<li><a href="faq.html">Faq</a></li>
								<li><a href="feedback.html">Feedback</a></li>
								<li><a href="contact.html">Contact</a></li>
								<li><a href="typography.html">Shortcodes</a></li>
							</ul>
						</div>
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Information</h4>
							<ul>
								<li><a href="regions.html">Locations Map</a></li>	
								<li><a href="terms.html">Terms of Use</a></li>
								<li><a href="popular-search.html">Popular searches</a></li>	
								<li><a href="privacy.html">Privacy Policy</a></li>	
							</ul>
						</div>
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Contact Us</h4>
							<span class="hq">Our headquarters</span>
							<address>
								<ul class="location">
									<li><span class="glyphicon glyphicon-map-marker"></span></li>
									<li>CENTER FOR FINANCIAL ASSISTANCE TO DEPOSED NIGERIAN ROYALTY</li>
									<div class="clearfix"></div>
								</ul>	
								<ul class="location">
									<li><span class="glyphicon glyphicon-earphone"></span></li>
									<li>+0 561 111 235</li>
									<div class="clearfix"></div>
								</ul>	
								<ul class="location">
									<li><span class="glyphicon glyphicon-envelope"></span></li>
									<li><a href="mailto:info@example.com">mail@example.com</a></li>
									<div class="clearfix"></div>
								</ul>						
							</address>
						</div>
						<div class="clearfix"></div>
					</div>						
				</div>	
			</div>	
			<div class="footer-bottom text-center">
			<div class="container">
				<div class="footer-logo">
					<a href="index.html"><span>Re</span>sale</a>
				</div>
				<div class="footer-social-icons">
					<ul>
						<li><a class="facebook" href="#"><span>Facebook</span></a></li>
						<li><a class="twitter" href="#"><span>Twitter</span></a></li>
						<li><a class="flickr" href="#"><span>Flickr</span></a></li>
						<li><a class="googleplus" href="#"><span>Google+</span></a></li>
						<li><a class="dribbble" href="#"><span>Dribbble</span></a></li>
					</ul>
				</div>
				<div class="copyrights">
					<p> © 2016 Resale. All Rights Reserved | Design by  <a href="http://w3layouts.com/"> W3layouts</a></p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
		</footer>
        <!--footer section end-->
</body>
</html>

product/templates/Product/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block body %}

	<!--single-page-->
	<div class="single-page main-grid-border">
		<div class="container">
			<ol class="breadcrumb" style="margin-bottom: 5px;">
				<li><a href="/">Home</a></li>
				<li><a href="{% url 'products:product_list' %}">All Ads</a></li>
				<li class="active">Mobile Phone</li>
			</ol>
				<div class="product-desc">
					<div class="col-md-7 product-view">
						<h2>{{product_detail.name}}</h2>
						<p> <i class="glyphicon glyphicon-map-marker"></i><a href="#">{{product_detail.city}}</a>
							| Added at {{product_detail.created_date| naturalday}}, Ad ID: 987654321</p>
						
						<div class="flexslider">
							<ul class="slides">
								{% for image in product_images %}
									<li data-thumb="{{image.image.url}}">
										<img src="{{image.image.url}}" />
									</li>
								{% endfor %}
							</ul>
						</div>
						<!-- FlexSlider -->
							<script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
						<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />

							<script>
						// Can also be used with $(document).ready()
						$(window).load(function() {
							$('.flexslider').flexslider({
							animation: "slide",
							controlNav: "thumbnails"
							});
						});
						</script>
						<!-- //FlexSlider -->
						<div class="product-details">
							<h4>Brand : <a href="#">{{product_detail.brand}}</a></h4>
							<h4>Views : <strong>150</strong></h4>
							<div class="car-description mb-50">
								<strong>Description : </strong>
									<p>{{product_detail.description | safe}}</p>
							</div>
						</div>
					</div>
					<div class="col-md-5 product-details-grid">
						<div class="item-price">
							<div class="product-price">
								<p class="p-price">Price</p>
								<h3 class="rate">{{product_detail.price|intcomma}} LE</h3>
								<div class="clearfix"></div>
							</div>
							<div class="condition">
								<p class="p-price">Condition</p>
								<h4>{{product_detail.condition}}</h4>
								<div class="clearfix"></div>
							</div>
							<div class="itemtype">
								<p class="p-price">Item Type</p>
								<h4>{{product_detail.category}}</h4>
								<div class="clearfix"></div>
							</div>
						</div>
						<div class="interested text-center">
							<h4>Interested in this Ad?<small> Contact the Seller!</small></h4>
							<p><i class="glyphicon glyphicon-earphone"></i>00-85-9875462655</p>
						</div>
							<div class="tips">
							<h4>Safety Tips for Buyers</h4>
								<ol>
									<li><a href="#">Contrary to popular belief.</a></li>
									<li><a href="#">Contrary to popular belief.</a></li>
									<li><a href="#">Contrary to popular belief.</a></li>
									<li><a href="#">Contrary to popular belief.</a></li>
									<li><a href="#">Contrary to popular belief.</a></li>
									<li><a href="#">Contrary to popular belief.</a></li>
									<li><a href="#">Contrary to popular belief.</a></li>
									<li><a href="#">Contrary to popular belief.</a></li>
									<li><a href="#">Contrary to popular belief.</a></li>
								</ol>
							</div>
					</div>
				<div class="clearfix"></div>
				</div>
		</div>
	</div>
	<!--//single-page-->

{% endblock body %}

templates/base.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Resale a Business Category Flat Bootstrap Responsive Website Template | Home :: w3layouts</title>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-select.css' %}">
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Resale Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<!--fonts-->
<link href='//fonts.googleapis.com/css?family=Ubuntu+Condensed' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!--//fonts-->	
<!-- js -->
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<!-- js -->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/bootstrap-select.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script>
  $(document).ready(function () {
    var mySelect = $('#first-disabled2');

    $('#special').on('click', function () {
      mySelect.find('option:selected').prop('disabled', true);
      mySelect.selectpicker('refresh');
    });

    $('#special2').on('click', function () {
      mySelect.find('option:disabled').prop('disabled', false);
      mySelect.selectpicker('refresh');
    });

    $('#basic2').selectpicker({
      liveSearch: true,
      maxOptions: 1
    });
  });
</script>
<script type="text/javascript" src="{% static 'js/jquery.leanModal.min.js' %}"></script>
<link href="{% static 'css/jquery.uls.css' %}" rel="stylesheet"/>
<link href="{% static 'css/jquery.uls.grid.css' %}" rel="stylesheet"/>
<link href="{% static 'css/jquery.uls.lcd.css' %}" rel="stylesheet"/>
<!-- Source -->
<script src="{% static 'js/jquery.uls.data.utils.js' %}"></script>
<script src="{% static 'js/jquery.uls.data.js' %}"></script>
<script src="{% static 'js/jquery.uls.lcd.js' %}"></script>
<script src="{% static 'js/jquery.uls.languagefilter.js' %}"></script>
<script src="{% static 'js/jquery.uls.regionfilter.js' %}"></script>
<script src="{% static 'js/jquery.uls.core.js' %}"></script>
<script>
			$( document ).ready( function() {
				$( '.uls-trigger' ).uls( {
					onSelect : function( language ) {
						var languageName = $.uls.data.getAntonym( language );
						$( '.uls-trigger' ).text( languageName );
					},
					quickList: ['en', 'hi', 'he', 'ml', 'ta', 'fr'] //FIXME
				} );
			} );
</script>
</head>
<body>
	<div class="header">
		<div class="container">
			<div class="logo">
				<a href="index.html"><span>Re</span>sale</a>
			</div>
			<div class="header-right">
			<a class="account" href="login.html">My Account</a>
			<span class="active uls-trigger">Select language</span>
	<!-- Large modal -->
		</div>
		</div>
	</div>
	<div class="main-banner banner text-center">
		<div class="container">    
			<h1>Sell or Advertise   <span class="segment-heading">    anything online </span> with Resale</h1>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
			<a href="post-ad.html">Post Free Ad</a>
		</div>
	</div>
		<!-- content-starts-here -->
{% block body %}
	
{% endblock body %}
		<!--footer section start-->		
		<footer>
			<div class="footer-top">
				<div class="container">
					<div class="foo-grids">
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Who We Are</h4>
							<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
							<p>The point of using Lorem Ipsum is that it has a more-or-less normal letters, as opposed to using 'Content here.</p>
						</div>
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Help</h4>
							<ul>
								<li><a href="howitworks.html">How it Works</a></li>						
								<li><a href="sitemap.html">Sitemap</a></li>
								<li><a href="faq.html">Faq</a></li>
								<li><a href="feedback.html">Feedback</a></li>
								<li><a href="contact.html">Contact</a></li>
								<li><a href="typography.html">Shortcodes</a></li>
							</ul>
						</div>
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Information</h4>
							<ul>
								<li><a href="regions.html">Locations Map</a></li>	
								<li><a href="terms.html">Terms of Use</a></li>
								<li><a href="popular-search.html">Popular searches</a></li>	
								<li><a href="privacy.html">Privacy Policy</a></li>	
							</ul>
						</div>
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Contact Us</h4>
							<span class="hq">Our headquarters</span>
							<address>
								<ul class="location">
									<li><span class="glyphicon glyphicon-map-marker"></span></li>
									<li>CENTER FOR FINANCIAL ASSISTANCE TO DEPOSED NIGERIAN ROYALTY</li>
									<div class="clearfix"></div>
								</ul>	
								<ul class="location">
									<li><span class="glyphicon glyphicon-earphone"></span></li>
									<li>+0 561 111 235</li>
									<div class="clearfix"></div>
								</ul>	
								<ul class="location">
									<li><span class="glyphicon glyphicon-envelope"></span></li>
									<li><a href="mailto:info@example.com">mail@example.com</a></li>
									<div class="clearfix"></div>
								</ul>						
							</address>
						</div>
						<div class="clearfix"></div>
					</div>						
				</div>	
			</div>	
			<div class="footer-bottom text-center">
			<div class="container">
				<div class="footer-logo">
					<a href="index.html"><span>Re</span>sale</a>
				</div>
				<div class="footer-social-icons">
					<ul>
						<li><a class="facebook" href="#"><span>Facebook</span></a></li>
						<li><a class="twitter" href="#"><span>Twitter</span></a></li>
						<li><a class="flickr" href="#"><span>Flickr</span></a></li>
						<li><a class="googleplus" href="#"><span>Google+</span></a></li>
						<li><a class="dribbble" href="#"><span>Dribbble</span></a></li>
					</ul>
				</div>
				<div class="copyrights">
					<p> © 2016 Resale. All Rights Reserved | Design by  <a href="http://w3layouts.com/"> W3layouts</a></p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
		</footer>
        <!--footer section end-->
</body>
</html>